language: node_js
node_js:
- '8'
cache: yarn:true
install:
  - npm install -g codecov
  - yarn install
script:
- yarn test
- codecov
- yarn build
env:
- CI=false
branches:
  only:
  - master
  - add-first-version
deploy:
  provider: npm
  email: "razvan@centrifuge.io"
